spring.application.name=ajarul
server.port=${PORT:8080}
# spring.datasource.url=jdbc:postgresql://localhost:5432/home_automation
spring.datasource.url=jdbc:postgresql://ep-plain-silence-ao0uj8jn-pooler.c-2.ap-southeast-1.aws.neon.tech/home_automation?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zCxT6KlP9EoN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
jwt.secret=mysecretkeymysecretkeymysecretkey123456

